name: Branch prefix check
on: [pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch prefix
        run: |
          if ! [[ "${{ github.head_ref }}" =~ ^(feat|fix|docs|chore)/[0-9]+- ]]; then
            echo "❌ Branch must start with feat/, fix/, docs/ or chore/ and an issue number"
            exit 1
          fi